# Generated by Django 2.1.5 on 2019-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aminoacidosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.FloatField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('cantidadServicios', models.IntegerField(max_length=50)),
                ('presentacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='glutaminasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.FloatField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='proteinasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.FloatField(max_length=100)),
                ('gramos', models.FloatField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('carbohidratos', models.FloatField(max_length=50)),
                ('servicios', models.IntegerField(max_length=40)),
                ('gramosProteinas', models.FloatField(max_length=40)),
            ],
        ),
    ]
